### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by AasheeshT**
@cvvergara @anitagraser 
As part of my GSoC 2018 preparation, i was asked to understand pgRoutingLayer code and comment what i understand. I have also added a file 'overview.txt' which will help beginners like me to understand the code better. In 'overview.txt' I have listed some of the resources which were helpful for me in understanding the code.

### CODE REVIEW

**Comment by dkastl** [comment]
Thank you @AasheeshT !

@cvvergara , just saw the "Codacy" check for pull requests is also enabled for this repository, but it seems to complain about issues, that are not relevant to documentation. Any reason to have Codacy checks enabled for this repository? They are a bit noisy ;-)

**Comment by cvvergara** [comment]
they are a lot noisy
Can you remove that check please

**Comment by cvvergara** [comment]
@AasheeshT 
I am not so sure about the overview file, you see we need to follow QGIS regulations.
And, if you are going to rewrite, I suggest that you use the contents of that file in your proposal, together with how that would change when making the new version.

FYI, the contents of that overview looks ok

**Comment by AasheeshT** [comment]
@cvvergara  code is working fine on my pc. And i changed commenting style.

**Comment by cvvergara** [comment]
@pwerspire 
We are just going to use your PR as part of the GSoC preparation.
If you get selected, then the code will change.
If you dont get selected, and the code does not change then we can talk about how code is documented.

**Pull request closed without merging**
